### ISSUE TITLE
Not a HASH reference at ./rfr.pl line 441

### ISSUE THREAD

**Issue by SJ50** [vortigont/rfr#1]
I am getting following error
rtorrent/libtorrent version 0.9.6/0.13.6

```` $  ./rfr.pl -v --session ~/rtorrent/.session_rfr_test

====
Processing file 00EA6EF663937A4BE856761F71C9E3AE73DE1298.torrent
Loading file - 00EA6EF663937A4BE856761F71C9E3AE73DE1298.torrent with coerce=1
Not a HASH reference at ./rfr.pl line 441.

**Comment by vortigont** [comment]
a bit outdated issue :) pls, reopen if still needed

**Comment by srdjanrosic** [comment]
yep, still an issue:

```
/rfr/rfr.pl -v --session .

====
Processing file 00D2D2655ECD7AD2B897CC88014738D524435984.torrent
Loading file - 00D2D2655ECD7AD2B897CC88014738D524435984.torrent with coerce=1
Not a HASH reference at /rfr/rfr.pl line 441.
```

**Comment by vortigont** [comment]
@srdjanrosic I suspect that `00D2D2655ECD7AD2B897CC88014738D524435984.torrent.libtorrent_resume` side file is either missing or corrupted or zero length. Could you pls check?
If that is the case than I can come up with some additional sanity check here

**Comment by srdjanrosic** [comment]
Is it possible, since I'm using docker, that somehow relative / absolute paths are confusing rfr.pl ?

I'm really not a perl expert, and I generally try to avoid perl as much as possible, so when I ran into errors I suspected perhaps my environment was broken somehow, but it just kind of refuses to decode any file in a clean docker environment.

Maybe the underlying C library for bencode parsing is buggy on aarch64?

I'm using rtorrent-0.9.8 / libtorrent 0.13.8 ... from alpine, running in a different docker container with a relatively minimalistic rtorrent.rc

```
# for this testing, just make a copy of rtorrent session from a running install
# ... and nuke the .lock file, to bypass the rfr.pl startup checks


cp -rv "${RTORRENT_SESSION_DIR:?}" -T /dev/shm/repro-rfr-issue1 ; rm /dev/shm/repro-rfr-issue1/rtorrent.lock

# $PWD is where we git cloned the rfr repo
# we happen to be running on aarch64, I suspect amd64 has the same issue
docker run --rm -it -v /dev/shm/rtorrent-rfr-repro:/rtorrent -v $PWD:/rfr arm64v8/debian /bin/bash

apt -y update

# eatmydata prevent sync-ing for this ephemeral container, makes apt faster
apt -y install eatmydata
exec eatmydata /bin/bash

apt -y install perl build-essential

PERL_MM_USE_DEFAULT=1 cpan -i Digest::SHA1
PERL_MM_USE_DEFAULT=1 cpan -i Convert::Bencode_XS  # fails, seems like a known issue

# the above fails in make test ... for some(?) reason?
# there's some instructions here:
# https://github.com/rakshasa/rtorrent/issues/489

mkdir -p ~/src
apt -y install wget

# the rest is from the issue 489 above, but maybe the tests were onto something
cd ~/src
wget http://search.cpan.org/CPAN/authors/id/I/IW/IWADE/Convert-Bencode_XS-0.06.tar.gz
wget https://rt.cpan.org/Ticket/Attachment/1433449/761974/patch-t_001_tests_t
tar zxf Convert-Bencode_XS-0.06.tar.gz
cd Convert-Bencode_XS-0.06
patch -uNp0 -i ../patch-t_001_tests_t
perl Makefile.PL
make
make test
make install

# /rfr/rfr.pl now works-ish - runnning it shows usage info


/rfr/rfr.pl -vs /rtorrent
# returns:

# ====
# Processing file 00D2D2655ECD7AD2B897CC88014738D524435984.torrent
# Loading file - 00D2D2655ECD7AD2B897CC88014738D524435984.torrent with coerce=1
# Not a HASH reference at ./rfr.pl line 441.

```

This is a running install after all, but the file decodes fine in other tools?

Can you try to reproduce on your end?

**Comment by vortigont** [comment]
You know, it's been really really long time since I've wrote this script :))) Good old days with perl and no any docker's around :))) Now I could hardly read my own code. Thanks for reminding me about it )
Nice to see that somebody could still use this script.
Should be fine now, pls check latest commit.
